import Head from "next/head";
import QuestionInput from "@/components/QuestionComponents/QuestionInput";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QuestionInput
        fe_id={"123"}
        props={{ title: "test", placeholder: "test" }}
      />
    </>
  );
}
