import Head from "next/head";
import QuestionInput from "@/components/QuestionComponents/QuestionInput";
import QuestionRadio from "@/components/QuestionComponents/QuestionRadio";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QuestionInput
        fe_id={"123"}
        props={{ title: "test", placeholder: "test" }}
      />
      <QuestionRadio
        fe_id={"123"}
        props={{
          title: "test",
          options: [
            { label: "test1", value: "test1" },
            { label: "test2", value: "test2" },
            { label: "test3", value: "test3" },
          ],
          value: "test",
          vertical: true,
        }}
      />
    </>
  );
}
